### PR TITLE
Replace ignore function by `let _ =`.

### PR DESCRIPTION
**Pull request by m-ou-se**

### CODE REVIEW

**Comment by de-vri-es** [comment]
I kinda like the explicitness of `ignore(foo)`. That's why I added it.

**Comment by de-vri-es** [comment]
hmm, nevermind. Maybe if `std` ever grows an `ignore` function.

**Comment by m-ou-se** [comment]
It has `drop()` :)

But `let _ = ` already means exactly 'ignore this', so I don't think the standard library would ever get anything like `ignore()`.

**Comment by de-vri-es** [comment]
Bit cryptic for my taste though, but yeah.

**Pull request merged**
