### PR TITLE
Set MSRV to 1.70

### PR DESCRIPTION
**Pull request by ilaborie**
Usage of `Option::is_some_and` requires Rust `1.70.0`

https://doc.rust-lang.org/std/option/enum.Option.html#method.is_some_and

### CODE REVIEW

**Comment by de-vri-es** [comment]
Ahh, oops. Good catch! Thanks for the PR!

I think I prefer to change the code to avoid `is_some_and()` though, and keep the MSRV on `1.65`. Would you like to adjust the PR to remove `is_some_and()`?

I will also look into having CI catch this in the future, by adding jobs for the MSRV in addition to latest stable and nightly.

**Comment by ilaborie** [comment]
I can do these changes

**Comment by ilaborie** [comment]
I've done a minimal check of MSRV.
You can adapt the code to your needs.

**Comment by de-vri-es** [comment]
Thanks, looks good!

**Comment by de-vri-es** [comment]
Released as 0.3.14. Thanks again! :partying_face:

**Pull request merged**
